name: Run Tests
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    env:
      TESTING: true
    steps:
      - name: Check Repository
        uses: actions/ckeckout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.6.8'

      - name: Setup Python Virtual Enviroment
        run: python -m venv python3-virtualenv

      - name: Install Dependencies
        run: python3-virtualenv/bin/pip install -r requirements.txt

      - name: Run Tests
        run: ./run_test.sh